// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Note: this build's `datasource` config only supports `url` (and
  // `shadowDatabaseUrl`) — there's no `directUrl` field. Supabase's pooled
  // connection can't run DDL, so `prisma migrate` commands must be run with
  // `--url "$DIRECT_URL"` to hit the direct (non-pooled) connection instead.
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
